//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercioDigital.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eCommerceEntitiesDB : DbContext
    {
        public eCommerceEntitiesDB()
            : base("name=eCommerceEntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Musicas> Bolsos { get; set; }
        public virtual DbSet<Calzados> Calzados { get; set; }
        public virtual DbSet<Carritos> Carritos { get; set; }
        public virtual DbSet<Joyas> Joyas { get; set; }
        public virtual DbSet<Modas> Modas { get; set; }
        public virtual DbSet<Moviles> Moviles { get; set; }
        public virtual DbSet<Multimedias> Multimedias { get; set; }
        public virtual DbSet<Musicas> Musicas { get; set; }
        public virtual DbSet<Ordenadores> Ordenadores { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<Peliculas> Peliculas { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Ropas> Ropas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tecnologicos> Tecnologicos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vendedores> Vendedores { get; set; }
        public virtual DbSet<Videoconsolas> Videoconsolas { get; set; }
        public virtual DbSet<Videojuegos> Videojuegos { get; set; }
        public virtual DbSet<Almacenes> Almacenes { get; set; }
    }
}
