//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercioDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modas
    {
        public int Id { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
        public string Sexo { get; set; }
    
        public virtual Musicas Bolsos { get; set; }
        public virtual Calzados Calzados { get; set; }
        public virtual Joyas Joyas { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Ropas Ropas { get; set; }
    }
}
