//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercioDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moviles
    {
        public int Id { get; set; }
        public Nullable<int> IdTecnologia { get; set; }
        public Nullable<double> Pantalla { get; set; }
        public Nullable<int> Bateria { get; set; }
    
        public virtual Tecnologicos Tecnologicos { get; set; }
    }
}
