//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercioDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moviles
    {
        public int Id { get; set; }
        public double Pantalla { get; set; }
        public int Bateria { get; set; }
    
        public virtual Tecnologicos Tecnologicos { get; set; }

        public static implicit operator Moviles(Productos v)
        {
            Moviles resul = new Moviles();
            resul.Tecnologicos = new Tecnologicos();
            resul.Tecnologicos.Productos = new Productos();
            resul.Tecnologicos.Productos.Id = v.Id;
            resul.Tecnologicos.Productos.Nombre = v.Nombre;
            resul.Tecnologicos.Productos.Precio = v.Precio;
            resul.Tecnologicos.Productos.Marca = v.Marca;
            resul.Tecnologicos.Productos.IdVendedor = v.IdVendedor;
            resul.Tecnologicos.Productos.Descripcion = v.Descripcion;
            resul.Tecnologicos.Productos.Valoracion = v.Valoracion;
            resul.Tecnologicos.Productos.FechaPuestaVenta = v.FechaPuestaVenta;
            resul.Tecnologicos.Productos.CodigoDescuento = v.CodigoDescuento;
            resul.Tecnologicos.Productos.Stock = v.Stock;
            resul.Tecnologicos.Color = v.Tecnologicos.Color;
            resul.Tecnologicos.Procesador = v.Tecnologicos.Procesador;
            resul.Tecnologicos.SistemaOperativo = v.Tecnologicos.SistemaOperativo;
            resul.Tecnologicos.Modelo = v.Tecnologicos.Modelo;
            resul.Tecnologicos.FechaLanzamiento = v.Tecnologicos.FechaLanzamiento;
            resul.Pantalla = v.Tecnologicos.Moviles.Pantalla;
            resul.Bateria = v.Tecnologicos.Moviles.Bateria;


            return resul;
        }
    }
}
