//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercioDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multimedias
    {
        public int Id { get; set; }
        public string Genero { get; set; }
        public string Formato { get; set; }
        public string Idioma { get; set; }
        public System.DateTime FechaLanzamiento { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Musicas Musicas { get; set; }
        public virtual Peliculas Peliculas { get; set; }
        public virtual Videojuegos Videojuegos { get; set; }
    }
}
