//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercioDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnologicos
    {
        public int Id { get; set; }
        public string Color { get; set; }
        public string Procesador { get; set; }
        public string SistemaOperativo { get; set; }
        public string Modelo { get; set; }
        public System.DateTime FechaLanzamiento { get; set; }
    
        public virtual Moviles Moviles { get; set; }
        public virtual Ordenadores Ordenadores { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Videoconsolas Videoconsolas { get; set; }
    }
}
