//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercioDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Pass { get; set; }
        public string Domicilio { get; set; }
        public decimal Saldo { get; set; }
        public int IdCarrito { get; set; }
        public Nullable<int> IdPedido { get; set; }
    
        public virtual Carritos Carritos { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
